### ISSUE TITLE
一个现有的二次元过头的对话库

### ISSUE THREAD

**Issue by HiDolen** [LorisYounger/ChatVPet#2]
[这个项目](https://github.com/Kyomotoi/AnimeThesaurus)是用于 bot 的对话库，拥有大量问答料库。

应该能帮助训练，或是辅助思考合适的问答。毕竟凭空想不是很容易（（

希望能派上用场

**Comment by LorisYounger** [comment]
确实很有意思, 不过桌宠目前还是以自己收集的训练为主. 不过这个我可以先自己拿来偷偷练练玩玩看看效果(

**Comment by LorisYounger** [comment]
或者筛选下塞到桌宠小法庭库里让大家投票, 先留着这个

**Comment by LorisYounger** [comment]
仔细研究了下, 不是一个很适合拿来训练ChatVPet, 虽然说里面有部分数据还是让人眼前一亮的
主要还是人设和性格方面有点冲突, 以及夹杂太多不相关的数据
不过我也是顺手数据整理了(全部数据塞一起)下拿出来练了练, 就当练手了, 明天后天看看效果

**Comment by HiDolen** [comment]
我最近也在学习llm微调。目前确定的思路是用轻小说进行增量预训练，然后主要用gal语料有监督微调。做着做着不禁感叹，语料真难筛啊，索性不筛而是相信llm的泛化能力（

这样的微调肯定不很容易，请加油！

既然已经传达了信息，我关闭这个 issue。

**Comment by HiDolen** [comment]
我觉得我们可以一起学习模型微调。要不留个联系方式
